// Copyright 2017-2021 @axia-js/networks authors & contributors
// SPDX-License-Identifier: Apache-2.0

import fs from 'fs';
import fetch from 'node-fetch';

const AXLIB_REGISTRY = 'https://raw.githubusercontent.com/axiatech/axlib/master/ss58-registry.json';

function outputField (v) {
  if (typeof v === 'string') {
    return `'${v}'`;
  } else if (Array.isArray(v)) {
    return `[${v.map((v) => outputField(v)).join(', ')}]`;
  }

  return v;
}

async function getAxlibRegistry () {
  const original = await fetch(AXLIB_REGISTRY);
  const json = await original.json();

  return json.registry
    .map((e) =>
      `  {\n${Object
        .entries(e)
        .sort(([a], [b]) => a.localeCompare(b))
        .map(([k, v]) => `    ${k}: ${outputField(v)}`)
        .join(',\n')}\n  }`
    )
    .join(',\n');
}

getAxlibRegistry()
  .then((entries) => {
    fs.writeFileSync('packages/networks/src/axlib.ts', `// Copyright 2017-2021 @axia-js/networks authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Auto-generated by yarn networks:sync (via scripts/fromAxlib.mjs)
//
// Do not edit, rather
//   - make a PR to the upstream registry as per ${AXLIB_REGISTRY}
//   - yarn networks:sync
//

import type { KnownAxlib } from './types';

export const knownAxlib: KnownAxlib[] = [\n${entries}\n];
`);

    console.log('Completed.');

    process.exit(0);
  })
  .catch((error) => {
    console.error('Error:', error.message);

    process.exit(-1);
  });
